export const en = {
    "Menu.Tabs.History": "History",
    "Menu.Tabs.FeedDetails": "Feed details",
    "Login.Title.SignIn": "Authorization",
    "Login.Title.SignUp": "Registration",
    "Login.Validation.Field.Required": "Should not be empty",
    "Login.Fields.Login": "Login",
    "Login.Fields.Password": "Password",
    "Login.Fields.ConfirmPassword": "Confirm password",
    "Login.Fields.OldPassword": "Current password",
    "Login.Fields.Name": "Name",
    "Login.Buttons.SignIn": "Sign In",
    "Login.Buttons.SignUp": "Sign Up",

    "Account.Buttons.Save": "Save",
    "Account.Loc.Label": "Language",
    "Account.Loc.Ru": "Russian",
    "Account.Loc.En": "English",

    "Messages.NoDataFound": "No data found",

    "FeedItem.Card.Buttons.Edit": "Edit",
    "FeedItem.Card.Buttons.Remove": "Remove",

    "FeedItem.Card.Edit.Title": "Edit feed item",
    "FeedItem.Card.Edit.Fields.Timestamp": "Time",
    "FeedItem.Card.Edit.Fields.Timestamp.Placeholder": "hh:mm",
    "FeedItem.Card.Edit.Fields.Timestamp.Required": "Time field should not be empty",
    "FeedItem.Card.Edit.Buttons.Save": "Save",
    "FeedItem.Card.Edit.Buttons.Cancel": "Cancel",

    "FeedItem.Card.Remove.Title": "Removing feed item",
    "FeedItem.Card.Remove.Message": "Do you really want to remove selected feed item?",
    "FeedItem.Card.Remove.Buttons.Yes": "Yes",
    "FeedItem.Card.Remove.Buttons.No": "No",

    "FeedItem.Card.Create.Title": "Create feed item",

    "FeedDetails.Card.Edit.Title": "Edit feed details item",
    "FeedDetails.Card.Create.Title": "Create feed details item",
    "FeedDetails.Card.Buttons.Edit": "Edit",
    "FeedDetails.Card.Buttons.Remove": "Remove",

    "FeedDetails.Card.Remove.Title": "Removing feed details item",
    "FeedDetails.Card.Remove.Message": "Do you really want to remove selected feed details item?",
    "FeedDetails.Card.Remove.Buttons.Yes": "Yes",
    "FeedDetails.Card.Remove.Buttons.No": "No",

    "FeedDetails.Card.Edit.Buttons.Save": "Save",
    "FeedDetails.Card.Edit.Buttons.Cancel": "Cancel",
    "FeedDetails.Card.Edit.Fields.Name": "Name",
    "FeedDetails.Card.Edit.Fields.Amount": "Amount",
    "FeedDetails.Card.Edit.Fields.AmountOfWhat": "Units",
    "FeedDetails.Card.Edit.Fields.Type": "Type",
    "FeedDetails.Card.Edit.Fields.WasGiven": "Was given to child",
    "FeedDetails.Card.Edit.Fields.Type.ValueWithAmount": "Value with amount",
    "FeedDetails.Card.Edit.Fields.Type.CheckedValue": "Checked value",
    "FeedDetails.Card.Edit.Fields.Name.Required": "Name field should not be empty",
    "FeedDetails.Card.Edit.Fields.Amount.Required": "Amount field should not be empty",
    "FeedDetails.Card.Edit.Fields.Amount.MoreThanZero": "Amount field should be more than 0",
    "FeedDetails.Card.Edit.Fields.AmountOfWhat.Required": "Units field should not be empty",
}